-- =============================================================================
-- Supplemental tables for Purchase Web System (NOT in APS_TBL.sql)
-- Prefix: PWS_ — run once on Oracle schema after APS_TBL.sql is deployed.
-- Does NOT modify or drop any existing IAS/APS tables.
-- =============================================================================

-- ─── Auth & RBAC ───────────────────────────────────────────────────────────

CREATE TABLE PWS_USER (
  USER_ID           VARCHAR2(42)   NOT NULL,
  USER_NO           VARCHAR2(30),
  EMAIL             VARCHAR2(120)  NOT NULL,
  USERNAME          VARCHAR2(60)   NOT NULL,
  PASSWORD_HASH     VARCHAR2(255)  NOT NULL,
  NAME_AR           VARCHAR2(100)  NOT NULL,
  NAME_EN           VARCHAR2(100),
  PHONE             VARCHAR2(20),
  IS_ACTIVE         NUMBER(1)      DEFAULT 1 NOT NULL,
  THEME_PREFERENCE  VARCHAR2(30),
  PRIMARY_COLOR     VARCHAR2(20),
  BRANCH_ID         VARCHAR2(42),
  DEPARTMENT_ID     VARCHAR2(42),
  ORACLE_U_ID       NUMBER(5),
  CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PWS_USER_PK PRIMARY KEY (USER_ID),
  CONSTRAINT PWS_USER_EMAIL_UK UNIQUE (EMAIL),
  CONSTRAINT PWS_USER_USERNAME_UK UNIQUE (USERNAME)
);

CREATE TABLE PWS_ROLE (
  ROLE_ID     VARCHAR2(42)  NOT NULL,
  CODE        VARCHAR2(60)  NOT NULL,
  NAME_AR     VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  IS_ACTIVE   NUMBER(1)     DEFAULT 1 NOT NULL,
  CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PWS_ROLE_PK PRIMARY KEY (ROLE_ID),
  CONSTRAINT PWS_ROLE_CODE_UK UNIQUE (CODE)
);

CREATE TABLE PWS_PERMISSION (
  PERM_ID     VARCHAR2(42)  NOT NULL,
  NAME        VARCHAR2(120) NOT NULL,
  NAME_AR     VARCHAR2(120) NOT NULL,
  MODULE      VARCHAR2(60)  NOT NULL,
  SCREEN_CODE VARCHAR2(60),
  ACTION      VARCHAR2(60),
  CONSTRAINT PWS_PERMISSION_PK PRIMARY KEY (PERM_ID),
  CONSTRAINT PWS_PERMISSION_NAME_UK UNIQUE (NAME)
);

CREATE TABLE PWS_USER_ROLE (
  USER_ID VARCHAR2(42) NOT NULL,
  ROLE_ID VARCHAR2(42) NOT NULL,
  CONSTRAINT PWS_USER_ROLE_PK PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT PWS_USER_ROLE_USER_FK FOREIGN KEY (USER_ID) REFERENCES PWS_USER (USER_ID) ON DELETE CASCADE,
  CONSTRAINT PWS_USER_ROLE_ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES PWS_ROLE (ROLE_ID) ON DELETE CASCADE
);

CREATE TABLE PWS_ROLE_PERMISSION (
  ROLE_ID VARCHAR2(42) NOT NULL,
  PERM_ID VARCHAR2(42) NOT NULL,
  CONSTRAINT PWS_ROLE_PERM_PK PRIMARY KEY (ROLE_ID, PERM_ID),
  CONSTRAINT PWS_ROLE_PERM_ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES PWS_ROLE (ROLE_ID) ON DELETE CASCADE,
  CONSTRAINT PWS_ROLE_PERM_PERM_FK FOREIGN KEY (PERM_ID) REFERENCES PWS_PERMISSION (PERM_ID) ON DELETE CASCADE
);

CREATE TABLE PWS_USER_PERMISSION (
  USER_ID VARCHAR2(42) NOT NULL,
  PERM_ID VARCHAR2(42) NOT NULL,
  EFFECT  VARCHAR2(10) DEFAULT 'allow' NOT NULL,
  CONSTRAINT PWS_USER_PERM_PK PRIMARY KEY (USER_ID, PERM_ID),
  CONSTRAINT PWS_USER_PERM_USER_FK FOREIGN KEY (USER_ID) REFERENCES PWS_USER (USER_ID) ON DELETE CASCADE,
  CONSTRAINT PWS_USER_PERM_PERM_FK FOREIGN KEY (PERM_ID) REFERENCES PWS_PERMISSION (PERM_ID) ON DELETE CASCADE
);

CREATE TABLE PWS_USER_SUPPLIER_PERM (
  USER_ID  VARCHAR2(42)    NOT NULL,
  V_CODE   VARCHAR2(15)    NOT NULL,
  CONSTRAINT PWS_USER_VNDR_PK PRIMARY KEY (USER_ID, V_CODE),
  CONSTRAINT PWS_USER_VNDR_USER_FK FOREIGN KEY (USER_ID) REFERENCES PWS_USER (USER_ID) ON DELETE CASCADE
);

-- ─── Approvals (web workflow — complements Oracle APPROVED flags) ────────────

CREATE TABLE PWS_APPROVAL_REQUEST (
  REQ_ID          VARCHAR2(42)  NOT NULL,
  REQ_NO          VARCHAR2(30)  NOT NULL,
  DOC_TYPE        VARCHAR2(40)  NOT NULL,
  DOC_SER         NUMBER(38),
  DOC_NO          NUMBER(15),
  STATUS          VARCHAR2(20)  DEFAULT 'pending' NOT NULL,
  REQUESTER_ID    VARCHAR2(42)  NOT NULL,
  REQUESTED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  COMPLETED_AT    TIMESTAMP,
  NOTES           VARCHAR2(1000),
  CONSTRAINT PWS_APPR_REQ_PK PRIMARY KEY (REQ_ID)
);

CREATE TABLE PWS_APPROVAL_ACTION (
  ACTION_ID    VARCHAR2(42) NOT NULL,
  REQ_ID       VARCHAR2(42) NOT NULL,
  STEP_ORDER   NUMBER(3)    NOT NULL,
  ACTOR_ID     VARCHAR2(42),
  ACTION       VARCHAR2(20),
  ACTION_AT    TIMESTAMP,
  COMMENTS     VARCHAR2(1000),
  CONSTRAINT PWS_APPR_ACT_PK PRIMARY KEY (ACTION_ID),
  CONSTRAINT PWS_APPR_ACT_REQ_FK FOREIGN KEY (REQ_ID) REFERENCES PWS_APPROVAL_REQUEST (REQ_ID) ON DELETE CASCADE
);

CREATE TABLE PWS_APPROVAL_MATRIX (
  MATRIX_ID    VARCHAR2(42) NOT NULL,
  DOC_TYPE     VARCHAR2(40) NOT NULL,
  BRANCH_ID    VARCHAR2(42),
  MIN_AMOUNT   NUMBER(24,9) DEFAULT 0,
  MAX_AMOUNT   NUMBER(24,9),
  IS_ACTIVE    NUMBER(1)    DEFAULT 1 NOT NULL,
  CONSTRAINT PWS_APPR_MATRIX_PK PRIMARY KEY (MATRIX_ID)
);

-- ─── Notifications ───────────────────────────────────────────────────────────

CREATE TABLE PWS_NOTIFICATION (
  NOTIF_ID     VARCHAR2(42)  NOT NULL,
  USER_ID      VARCHAR2(42)  NOT NULL,
  TITLE        VARCHAR2(200) NOT NULL,
  BODY         VARCHAR2(2000),
  ROUTE        VARCHAR2(500),
  ACTION_URL   VARCHAR2(500),
  IS_READ      NUMBER(1)     DEFAULT 0 NOT NULL,
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PWS_NOTIF_PK PRIMARY KEY (NOTIF_ID),
  CONSTRAINT PWS_NOTIF_USER_FK FOREIGN KEY (USER_ID) REFERENCES PWS_USER (USER_ID) ON DELETE CASCADE
);

CREATE INDEX PWS_NOTIF_USER_IDX ON PWS_NOTIFICATION (USER_ID, IS_READ, CREATED_AT);

-- ─── Supplier payment vouchers (not in APS_TBL.sql) ──────────────────────────

CREATE TABLE PWS_SUPPLIER_PAYMENT (
  PAY_SER       NUMBER(38)     NOT NULL,
  PAY_NO        NUMBER(15)     NOT NULL,
  PAY_DATE      DATE           NOT NULL,
  V_CODE        VARCHAR2(15)   NOT NULL,
  A_CY          VARCHAR2(7)    NOT NULL,
  EXCH_RATE     NUMBER         NOT NULL,
  PAY_AMOUNT    NUMBER(24,9)   NOT NULL,
  NOTES         VARCHAR2(1000),
  STATUS        VARCHAR2(20)   DEFAULT 'draft' NOT NULL,
  APPROVED      NUMBER(1)      DEFAULT 0 NOT NULL,
  POSTED        NUMBER(1)      DEFAULT 0 NOT NULL,
  APRV_U_ID     NUMBER(5),
  APRV_DATE     DATE,
  POST_U_ID     NUMBER(5),
  POST_DATE     DATE,
  AD_U_ID       VARCHAR2(42),
  AD_DATE       TIMESTAMP      DEFAULT SYSTIMESTAMP,
  UP_U_ID       VARCHAR2(42),
  UP_DATE       TIMESTAMP,
  CONSTRAINT PWS_SUP_PAY_PK PRIMARY KEY (PAY_SER)
);

CREATE TABLE PWS_SUPPLIER_PAY_ALLOC (
  ALLOC_ID      VARCHAR2(42)   NOT NULL,
  PAY_SER       NUMBER(38)     NOT NULL,
  BILL_SER      NUMBER(38)     NOT NULL,
  BILL_NO       NUMBER(15)     NOT NULL,
  ALLOC_AMOUNT  NUMBER(24,9)   NOT NULL,
  CONSTRAINT PWS_SUP_PAY_ALLOC_PK PRIMARY KEY (ALLOC_ID),
  CONSTRAINT PWS_SUP_PAY_ALLOC_PAY_FK FOREIGN KEY (PAY_SER) REFERENCES PWS_SUPPLIER_PAYMENT (PAY_SER) ON DELETE CASCADE
);

CREATE SEQUENCE PWS_SUP_PAY_SER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ─── Document usage tracking (web cascade — mirrors used-document.service) ───

CREATE TABLE PWS_DOC_USAGE (
  USAGE_ID      VARCHAR2(42) NOT NULL,
  SOURCE_TYPE   VARCHAR2(40) NOT NULL,
  SOURCE_SER    NUMBER(38)   NOT NULL,
  TARGET_TYPE   VARCHAR2(40) NOT NULL,
  TARGET_SER    NUMBER(38)   NOT NULL,
  CREATED_AT    TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PWS_DOC_USAGE_PK PRIMARY KEY (USAGE_ID)
);

CREATE INDEX PWS_DOC_USAGE_SRC_IDX ON PWS_DOC_USAGE (SOURCE_TYPE, SOURCE_SER);
CREATE INDEX PWS_DOC_USAGE_TGT_IDX ON PWS_DOC_USAGE (TARGET_TYPE, TARGET_SER);

-- ─── Audit log (web-level; Oracle has IAS_AUD_SYS_PKG for APS tables) ────────

CREATE TABLE PWS_AUDIT_LOG (
  LOG_ID       VARCHAR2(42)  NOT NULL,
  USER_ID      VARCHAR2(42),
  ACTION       VARCHAR2(60)  NOT NULL,
  ENTITY_TYPE  VARCHAR2(60),
  ENTITY_ID    VARCHAR2(60),
  DETAILS      CLOB,
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PWS_AUDIT_LOG_PK PRIMARY KEY (LOG_ID)
);

CREATE INDEX PWS_AUDIT_LOG_ENTITY_IDX ON PWS_AUDIT_LOG (ENTITY_TYPE, ENTITY_ID, CREATED_AT);

COMMIT;
